services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "${APP_PORT}:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      tracer:
        condition: service_healthy

  tracer:
    build:
      context: .
      dockerfile: docker/tracer/Dockerfile
    expose:
      - "8000"
    environment:
      - CORS_ORIGIN=${CORS_ORIGIN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
